version: '3'

services:
  web:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    command: airflow standalone
    depends_on:
      - db
  db:
    image: postgres:14.10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres